def run_please(self):
        self.input_comrade()
        self.list_comrades()
        self.input_commander()
        self.list_commanders()
        self.input_squad()
        self.input_mission()
        self.list_missions()
        self.commander_without_squad()
        self.comrade_without_squad()
program = Comrade_Information_Management_System()
program.run_please()